core/account/urls.py
from django.urls import path, reverse_lazy
from account import views
from django.contrib.auth import views as auth_views

app_name = "account"

urlpatterns = [
    # using django's built-in auth framework to handle authentication
    # login and logout urls
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    # change password urls
    path(
        "password-change/",
        auth_views.PasswordChangeView.as_view(
            success_url=reverse_lazy("account:password_change_done")
        ),
        name="password_change",
    ),
    path(
        "password-change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    # Reset password urls
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            success_url=reverse_lazy("account:password_reset_done")
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy("account:password_reset_complete")
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    # register user url
    path("register/", views.RegistrationView.as_view(), name="register"),
    # dashboard url
    path("", views.dashboard, name="dashboard"),
    path(
        "edit-profile/<int:pk>/", views.UpdateProfileView.as_view(), name="edit_profile"
    ),
    path("edit-user/<int:pk>/", views.UpdateUserView.as_view(), name="edit_user"),
]

core/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("account.urls")),
    path(
        "social-auth/",
        include("social_django.urls", namespace="social")
    ),
    path("image/", include("image.urls", namespace="image")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

core/image/urls.py
from django.urls import path
from image import views

app_name = "image"

urlpatterns = [
    path(
        "create/",
        views.ImageCreateView.as_view(),
        name="create"
    ),
    path(
        "detail/<int:id>/<slug:slug>/",
        views.ImageDetailView.as_view(),
        name="detail"
    ),
    path(
        "like/",
        views.ImageLikeView.as_view(),
        name="like"
    ),
    path(
        '',
        views.ImageListView.as_view(),
        name='list'
    ),
]

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href= "{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
    <div id="header">
        <span class="logo">Bookmarks</span>
        {% if request.user.is_authenticated %}
            <ul class="menu">
                <li {% if section == 'dashboard' %}class="selected"{% endif %}>
                    <a href="{% url "account:dashboard" %}">My dashboard</a>
                </li>
                <li {% if section == 'images' %}class="selected"{% endif %}>
                    <a href="{% url "image:list" %}">Images</a>
                </li>
                <li {% if section == 'people' %}class="selected"{% endif %}>
                    <a href="#">People</a>
                </li>
            </ul>
            <span class="user">
                {% if request.user.is_authenticated %}
                    Hello {{ request.user.first_name|default:request.user.email }},
                    <form action="{% url "account:logout" %}" method="post">
                        <button type="submit">Logout</button>
                        {% csrf_token %}
                    </form>
                {% else %}
                    <a href="{% url "account:login" %}">Log-in</a>
                {% endif %}
                </span>
        {% endif %}
    </div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">
                    {{ message|safe }}
                    <a href="#" class="close">x</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    <div class="content">
        {% block content %}{% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>
    <script>
        const csrftoken = Cookies.get('csrftoken');
        document.addEventListener('DOMContentLoaded', (event) => {
            // DOM loaded
            {% block domready %}
            {% endblock domready %}
        })
    </script>
</body>
</html>